apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels:
        app: counter-backend
    spec:
      containers:
      - name: counter-backend
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: database-user
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: database-name
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: database-password
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: counter-backend
                key: DB_HOST
        image: ghcr.io/dreamcat04/counter-backend:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080